
import turtle
turtle.color("purple")
turtle.forward (50)
turtle.left (90)
turtle.forward (50)
turtle.left (90)
turtle.forward (50)
turtle.left (90)
turtle.forward (50)
#turtle.left (90)
turtle.forward (50)
turtle.left (90)
turtle.forward (60)
turtle.left (90)
turtle.forward (50)
turtle.left (90)
turtle.forward (10)
turtle.penup()
turtle.right (180)
turtle.forward (50)
turtle.left (90)
turtle.forward (50)
turtle.pendown ()
turtle.right (160)
turtle.forward (100)
turtle.left (140)
turtle.forward(80)
turtle.right (140)
turtle.forward (80)
turtle.left (140)
turtle.forward (100)


